session_name: clip
windows:
- layout: fdd1,170x52,0,0{125x52,0,0,5,44x52,126,0,6}
  options: {}
  panes:
  - focus: 'true'
  - shell_command:
    - ./log.img.sh
  - shell_command:
    - ./gcloud/log.sh
  - shell_command:
    - htop
  start_directory: /root/gcloud
