session_name: clip
windows:
- layout: 9f46,241x65,0,0{62x65,0,0,0,61x65,63,0,2,116x65,125,0,1}
  options: {}
  panes:
  - focus: 'true'
  - shell_command:
    - ./log.img.sh
  - shell_command:
    - ./gcloud/log.sh
  - shell_command:
    - htop
  start_directory: /root/gcloud
